name: Test
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-13
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          set -ex
                
          brew install docker docker-compose colima
          colima start --runtime docker

          docker compose up --detach

          swift test
